### ISSUE TITLE
Ripple wallet disclaimer update

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-wallet#371]
We need to update the ripple wallet warning, to make it more understandable (ideally with a wiki article about the ripple deposit...)

![52953574-32a8c180-3388-11e9-959b-77508513c16d](https://user-images.githubusercontent.com/3112191/53006333-4fe79980-3435-11e9-9131-eed3488a7565.png)

**Comment by slowbackspace** [comment]
destination tag also needs some love
<img width="293" alt="screenshot 2019-01-15 at 13 30 49" src="https://user-images.githubusercontent.com/6961901/51180858-e02c3f00-18c9-11e9-8a43-c2052615e4fd.png">

**Comment by OliverBenT** [comment]
I'd keep it this simple. The rest of the details about the Base Reserve will follow in the Wiki article later this week.

"Ripple addresses require a minimum balance of 20 XRP to activate and maintain the account. [Learn more](https://wiki.trezor.io/Ripple_(XRP))"

"Destination tag is an arbitrary number which serves as a unique identifier of your transaction. Some services may require this to process your transaction. [Learn more](https://wiki.trezor.io/Ripple_(XRP))"

I recommend using "Learn more" instead of "Read more".
